# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inkshade < Formula
  desc "A CLI that masks PII and credentials in text streams"
  homepage "https://github.com/toritori0318/inkshade"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/toritori0318/inkshade/releases/download/v0.8.0/inkshade_darwin_amd64.tar.gz"
      sha256 "3dbe13892ca85913ce992182d038f91826a47de55a8ac3b760079bf25b5678fa"

      define_method(:install) do
        bin.install "inkshade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/toritori0318/inkshade/releases/download/v0.8.0/inkshade_darwin_arm64.tar.gz"
      sha256 "57d25edd65f9041955f9ffd30669f06a5da56fcc28c8f8ef810ca36e4515f655"

      define_method(:install) do
        bin.install "inkshade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/toritori0318/inkshade/releases/download/v0.8.0/inkshade_linux_amd64.tar.gz"
      sha256 "36b48ac842758979e631b5abbe73fbe9b779faaa213fce0f2a54e9705c5d7622"
      define_method(:install) do
        bin.install "inkshade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/toritori0318/inkshade/releases/download/v0.8.0/inkshade_linux_arm64.tar.gz"
      sha256 "d80449a8020a74804fff5a6cc83c78c2edb68b79b948728dfa5525ac6fdc7c44"
      define_method(:install) do
        bin.install "inkshade"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/inkshade --version")
  end
end
